dist: trusty
language: java
install: mvn install -DskipTests=true -Dgpg.skip=true

jdk:
  - openjdk8
  - openjdk11

notifications:
  email: false

# whitelist
branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
