dist: trusty
language: java
install: mvn install -DskipTests=true -Dgpg.skip=true

jdk:
  - openjdk8
  - openjdk11
  - openjdk14

notifications:
  email: false

# whitelist
branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
