<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.jodah</groupId>
    <artifactId>typetools</artifactId>
    <version>0.6.4-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>TypeTools</name>
    <url>http://github.com/jhalterman/typetools/</url>

    <description>A simple, zero-dependency library for working with types. Supports Java 1.6+ and Android.</description>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Jonathan Halterman</name>
            <url>http://jodah.net</url>
        </developer>
        <developer>
            <name>M.P. Korstanje</name>
            <email>rien.korstanje@gmail.com</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git@github.com:jhalterman/typetools.git</connection>
        <developerConnection>scm:git:git@github.com:jhalterman/typetools.git</developerConnection>
        <url>https://github.com/jhalterman/typetools/</url>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <project.build.outputTimestamp>1788287116</project.build.outputTimestamp>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.propertiesEncoding>UTF-8</project.build.propertiesEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <minimum.maven.version>3.9.0</minimum.maven.version>

        <!-- Maven plugin versions -->
        <maven-clean-plugin.version>3.5.0</maven-clean-plugin.version>
        <maven-compiler-plugin.version>3.16.0</maven-compiler-plugin.version>
        <maven-dependency-plugin.version>3.11.0</maven-dependency-plugin.version>
        <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>
        <maven-enforcer-plugin.version>3.6.3</maven-enforcer-plugin.version>
        <maven-failsafe-plugin.version>3.5.6</maven-failsafe-plugin.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <maven-install-plugin.version>3.1.4</maven-install-plugin.version>
        <maven-jar-plugin.version>3.5.1</maven-jar-plugin.version>
        <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
        <maven-release-plugin.version>3.3.1</maven-release-plugin.version>
        <maven-resources-plugin.version>3.5.0</maven-resources-plugin.version>
        <maven-site-plugin.version>3.22.0</maven-site-plugin.version>
        <maven-source-plugin.version>3.4.0</maven-source-plugin.version>
        <maven-surefire-plugin.version>3.5.6</maven-surefire-plugin.version>
        <maven-toolchains-plugin.version>3.3.0</maven-toolchains-plugin.version>

        <!-- Other Maven plugin versions -->
        <central-publishing-maven-plugin.version>0.11.0</central-publishing-maven-plugin.version>
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>
        <maven-bundle-plugin.version>6.2.0</maven-bundle-plugin.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.10</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Plugins are alphabetically ordered -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${maven-deploy-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven-failsafe-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>${maven-gpg-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${maven-release-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>${maven-site-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-toolchains-plugin</artifactId>
                    <version>${maven-toolchains-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>${maven-install-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>${central-publishing-maven-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco-maven-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>${maven-bundle-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce</id>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>[1.8,)</version>
                                </requireJavaVersion>
                                <requireMavenVersion>
                                    <version>[${minimum.maven.version},)</version>
                                </requireMavenVersion>
                                <requirePluginVersions>
                                    <message>Always define plugin versions!</message>
                                    <banLatest>true</banLatest>
                                    <banRelease>true</banRelease>
                                    <banSnapshots>true</banSnapshots>
                                    <phases>clean,deploy,site</phases>
                                </requirePluginVersions>
                            </rules>
                        </configuration>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <source>1.6</source>
                            <target>1.6</target>
                            <jdkToolchain>
                                <version>8</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk9-compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <release>9</release>
                            <jdkToolchain>
                                <version>11</version>
                            </jdkToolchain>
                            <multiReleaseOutput>true</multiReleaseOutput>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/src/main/java9</compileSourceRoot>
                            </compileSourceRoots>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk12-compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <release>12</release>
                            <jdkToolchain>
                                <version>17</version>
                            </jdkToolchain>
                            <multiReleaseOutput>true</multiReleaseOutput>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/src/main/java12</compileSourceRoot>
                            </compileSourceRoots>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk22-compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <release>22</release>
                            <jdkToolchain>
                                <version>25</version>
                            </jdkToolchain>
                            <multiReleaseOutput>true</multiReleaseOutput>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/src/main/java22</compileSourceRoot>
                            </compileSourceRoots>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <release>8</release>
                            <jdkToolchain>
                                <version>8</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Issue*.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>8</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Issue*.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-integration-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>8</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-11-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>11</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-11-test-with-add-opens</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <!-- Open module to push TypeResolverUtil to use
                                 MethodHandles.privateLookupIn.
                                 Note: ALL-UNNAMED should be net.jodah.typetools but failsafe
                                 doesn't put it on the module path.
                             -->
                            <argLine>
                                @{argLine}
                                --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.access=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
                            </argLine>
                            <jdkToolchain>
                                <version>11</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-17-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>17</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-17-test-with-add-opens</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <!-- Open module to push TypeResolverUtil to use
                                 MethodHandles.privateLookupIn.
                                 Note: ALL-UNNAMED should be net.jodah.typetools but failsafe
                                 doesn't put it on the module path.
                             -->
                            <argLine>
                                @{argLine}
                                --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.access=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
                            </argLine>
                            <jdkToolchain>
                                <version>17</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-21-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>21</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-21-test-with-add-opens</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <!-- Open module to push TypeResolverUtil to use
                                 MethodHandles.privateLookupIn.
                                 Note: ALL-UNNAMED should be net.jodah.typetools but failsafe
                                 doesn't put it on the module path.
                             -->
                            <argLine>
                                @{argLine}
                                --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.access=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
                            </argLine>
                            <jdkToolchain>
                                <version>21</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-25-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <jdkToolchain>
                                <version>25</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jdk-25-test-with-add-opens</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <!-- Deny unsafe memory access  and open module to
                                 push TypeResolverUtil to use MethodHandles.privateLookupIn.
                                 Note: ALL-UNNAMED should be net.jodah.typetools but failsafe
                                 doesn't put it on the module path.
                             -->
                            <argLine>
                                @{argLine}
                                --sun-misc-unsafe-memory-access=deny
                                --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.access=ALL-UNNAMED
                                --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
                            </argLine>
                            <jdkToolchain>
                                <version>25</version>
                            </jdkToolchain>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Multi-Release>true</Multi-Release>
                        </manifestEntries>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bundle-manifest</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <instructions>
                        <Implementation-Title>${project.description}</Implementation-Title>
                        <Implementation-Version>${project.version}</Implementation-Version>
                        <Bundle-Name>Type Tools</Bundle-Name>
                        <Bundle-SymbolicName>net.jodah.typetools</Bundle-SymbolicName>
                        <Export-Package>net/jodah/typetools;version=${project.version}</Export-Package>
                        <Import-Package>*</Import-Package>
                    </instructions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <sourcepath>${project.build.sourceDirectory}</sourcepath>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- Jacoco expects all classes to be unique, but
                             this class can't be unique because it is multi-released. -->
                        <exclude>**/META-INF/versions/**/TypeResolverUtil.class</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>prepare-agent-integration</id>
                        <goals>
                            <goal>prepare-agent-integration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report-integration</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-integration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-check-integration</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <dataFile>target/jacoco-it.exec</dataFile>
                            <rules>
                                <rule>
                                    <!-- All classes should be covered -->
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>CLASS</counter>
                                            <value>MISSEDCOUNT</value>
                                            <maximum>0</maximum>
                                        </limit>
                                    </limits>
                                </rule>
                                <rule>
                                    <!-- Nearly all instructions should be covered -->
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>INSTRUCTION</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.93</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <checksums>required</checksums>
                    <publishingServerId>central</publishingServerId>
                    <deploymentName>${project.artifactId}:${project.version}</deploymentName>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven-release-plugin.version}</version>
                <configuration>
                    <tagNameFormat>v@{project.version}</tagNameFormat>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
