name: build

permissions: {}

on: [push, pull_request]


env:
  MAVEN_ARGS: '--batch-mode -D"style.color=always"'

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11, 17, 21, 25 ]
        jdk: ['temurin', 'zulu']

    name: Java ${{ matrix.java }} ${{ matrix.jdk }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: ${{ matrix.jdk }}
          java-package: jdk
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with maven
        run: mvn verify
